### PR TITLE
Lion Optimizer

### PR DESCRIPTION
**Pull request by kamathis4**
In relation to [this](https://github.com/EleutherAI/gpt-neox/issues/950) issue

TODO:
-  Do you require the trition portion to be ported as well?

### CODE REVIEW

**Comment by Quentin-Anthony** [comment]
Thanks for working on this! Have you:

1. Tested the Lion optimizer with a very small model and seen loss decrease? Have you compared this decrease to Adam and seen the expected memory benefits? We tried to integrate Adafactor [here](https://github.com/EleutherAI/gpt-neox/pull/453) but didn't see the expected benefits and therefore didn't merge.
2. Sharded the optimizer with DeepSpeed ZeRO (just stage 1 is fine) and verified loss still decreases and nothing breaks

**Comment by StellaAthena** [comment]
@kamathis4 Hey, I wanted to follow up on this.

**Comment by kamathis4** [comment]
Sorry for the delay @StellaAthena, please assign it to someone else. Been really busy.

**Comment by ocss884** [comment]
@StellaAthena Hi Stella, I can help with the testing. I have sent you a DM in Discord.

**Comment by andylolu2** [comment]
Hey, I picked up with PR: fixed some bugs and did some tiny experiments #1062. Should we close this PR?
(My discord handle is BjergerK1ng#2545)

**Comment by Quentin-Anthony** [comment]
Resolved by https://github.com/EleutherAI/gpt-neox/pull/1062

**Pull request closed without merging**
