### PR TITLE
working minimal GPT

### PR DESCRIPTION
**Pull request by lucidrains**

### CODE REVIEW

**Review by ConnorJL — DISMISSED** [review]
Trying out this review feature.

Review: It's lucid's code, of course it's good lol. A good basis to start from.

**Comment by StellaAthena** [comment]
> Trying out this review feature.
> 
> Review: It's lucid's code, of course it's good lol. A good basis to start from.

Have you run it? I certainly wouldn't claim lucid doesn't write good code, but I wanted to check that it runs for someone else before approving it.

**Comment by ConnorJL** [comment]
I have now run the code on the servers, code runs, uses GPUs, loss goes down. One minor problem: No tqdm dependency in the requirements.txt

**Comment by StellaAthena** [comment]
> I have now run the code on the servers, code runs, uses GPUs, loss goes down. One minor problem: No tqdm dependency in the requirements.txt

If you start a new review, you should be able to request that change.

**Review by ConnorJL — CHANGES_REQUESTED** [review]
Requires adding of tqdm to requirements.txt

(Just testing out this new approval stuff, sorry for the hassle lucid lol)

**Review by ConnorJL — APPROVED** [review]
All good, ready to merge, thanks!

**Pull request merged**
