### PR TITLE
Add some comments and get rid of dead code

### PR DESCRIPTION
**Pull request by leogao2**

### CODE REVIEW

**Review by StellaAthena — CHANGES_REQUESTED** [review]
Please update from main and address the conflicts.

**Comment by StellaAthena** [comment]
Leo, I'm confused by your "get rid of dead code" changes. I started to revert it, but realized asking is probably a better idea than acting unilaterally lol. Why do you think we don't use `megatron/model/distributed.py`? It gets called by the main training loop!

**Review by StellaAthena — CHANGES_REQUESTED** [review]
Leo, I'm confused by your "get rid of dead code" changes. I started to revert it, but realized asking is probably a better idea than acting unilaterally lol. Why do you think we don't use `megatron/model/distributed.py`? It gets called by the main training loop! If that file is really dead code, then there's a significant amount of other dead code to remove as well.

Regardless, we cannot merge this into main as-is because it doesn't run. It immediately errors out with `ModuleNotFoundError: No module named 'megatron.model.distributed'`. If you want to remove `megatron/model/distributed.py` you need to make corresponding changes elsewhere so that the code can run.

**Comment by leogao2** [comment]
Can someone please review

**Review by sdtblck — APPROVED** [review]

**Pull request merged**
