### PR TITLE
 added shampoo optimizer from https://github.com/jettify/pytorch-opti…

### PR DESCRIPTION
**Pull request by rokosbasilisk**
…mizer/blob/master/torch_optimizer/shampoo.py

### CODE REVIEW

**Comment by rokosbasilisk** [comment]
okay, doing.

**Comment by StellaAthena** [comment]
> okay, doing.

Thanks!

**Comment by StellaAthena** [comment]
@rokosbasilisk any updates?

**Comment by rokosbasilisk** [comment]
added a sample config at configs/small_shampoo.yml

**Comment by StellaAthena** [comment]
I know I need to test and merge this, just haven’t gotten around to it :S Hopefully in the next couple days I can.

**Comment by StellaAthena** [comment]
Closing as too far behind main to be merged. May require substantial refactors to get working.

**Pull request closed without merging**
