### PR TITLE
Run eval harness during training

### PR DESCRIPTION
**Pull request by sdtblck**
addresses https://github.com/EleutherAI/gpt-neox/issues/366

The generation tasks aren't that fast - so best to stick to the log likelihood tasks (you can add them to the yaml with the "eval_tasks" parameter.

e.g

```yaml
"eval_tasks": ["lambada", "wikitext", "piqa"],
```

### CODE REVIEW

**Review by StellaAthena — CHANGES_REQUESTED** [review]
It looks like it's locking on piqa. We need to check out the HF dataset builder internals and make sure it's thread safe.

**Comment by StellaAthena** [comment]
__Notes on this PR's behavior:__
1. running just lambada works fine
2. running just piqa works fine

**Comment by StellaAthena** [comment]
mathqa + piqa has been running for over 8 hours without any problems. I’m wondering if the core problem is about mixing HF and non-HF tasks

**Comment by sdtblck** [comment]
Hey @StellaAthena can you test out the above change, and let me know if it makes a difference?
I try to pre-download all the tasks on local rank 0, to get rid of any multithreading problems

**Comment by StellaAthena** [comment]
> Hey @StellaAthena can you test out the above change, and let me know if it makes a difference?
> I try to pre-download all the tasks on local rank 0, to get rid of any multithreading problems

It's on today's TODO list :)

**Review by sweinbach — APPROVED** [review]

**Comment by sdtblck** [comment]
Just some peace of mind for @StellaAthena that this is definitely working :) 
Screenshot from 2021-08-31 16-36-22
Screenshot from 2021-08-31 16-38-07

**Review by StellaAthena — APPROVED** [review]

**Pull request merged**
