### PR TITLE
[Bug] Make Configs Consistent

### PR DESCRIPTION
**Pull request by austinburnett**
- #920 

**Checklist:**
- [x] I have added a warning that '-' may be deprecated in relevant readme.
- [x] I have updated all documentation to be consistent. Replacing all occurrences of '-' with '_'
- [x] I have modified demo files to also be consistent.

### CODE REVIEW

**Comment by StellaAthena** [comment]
Why isn't "I have modified demo files to also be consistent." marked as completed? It looks like it has been?

To be clear, that's referring to the files in `gpt-neox/configs`

**Comment by austinburnett** [comment]
> Why isn't "I have modified demo files to also be consistent." marked as completed? It looks like it has been?
> 
> To be clear, that's referring to the files in `gpt-neox/configs`

The reason this wasn't marked as complete was that I was unsure if these were the specific files you were referring to. I'll go ahead and check it off now that its been verified.

**Comment by austinburnett** [comment]
Looks like some of the checks are failing. I'll review my changes and make sure I didn't replace a '-' with a '_' that should've stayed a '-'.

**Comment by StellaAthena** [comment]
Try running `pre-commit run --all-files` locally

**Comment by austinburnett** [comment]
> Try running `pre-commit run --all-files` locally

Thanks! All checks passed locally for the new commit.

**Review by Quentin-Anthony — APPROVED** [review]
LGTM. I'll deal with the pre-commit checks in a separate PR.

@StellaAthena -- Take a look yourself and merge.

**Comment by austinburnett** [comment]
> LGTM. I'll deal with the pre-commit checks in a separate PR.
> 
> @StellaAthena -- Take a look yourself and merge.

LGTM!!!! Sounds good. If you don't mind, could you tell me what the issue was when it gets sorted out.... trying to learn as much as possible!

**Comment by Quentin-Anthony** [comment]
This will break every user config 

> > LGTM. I'll deal with the pre-commit checks in a separate PR.
> > @StellaAthena -- Take a look yourself and merge.
> 
> LGTM!!!! Sounds good. If you don't mind, could you tell me what the issue was when it gets sorted out.... trying to learn as much as possible!

Yep I'll let you know what it ends up being :)

**Comment by austinburnett** [comment]
> This will break every user config
> 
> > > LGTM. I'll deal with the pre-commit checks in a separate PR.
> > > @StellaAthena -- Take a look yourself and merge.
> > 
> > 
> > LGTM!!!! Sounds good. If you don't mind, could you tell me what the issue was when it gets sorted out.... trying to learn as much as possible!
> 
> Yep I'll let you know what it ends up being :)

Thank you!! I'd like to contribute on a programming-related issue shortly. I'll be busy the rest of this week preparing for interviews. If possible, could you point me to a good next issue to work on.

**Pull request merged**
