### PR TITLE
fix a GQA issue (#1314)

### PR DESCRIPTION
**Pull request by tiandeyu-cs**
fix a GQA issue (#1314)
- do not create a fake head dim and split the 'mixed_x_layer' into QKV layers directly.

### CODE REVIEW

**Review by Quentin-Anthony — APPROVED** [review]
Working for me. Nice catch.

**Comment by aflah02** [comment]
Hi @tiandeyu-cs 
I am facing issues while exporting a GQA model to HF (it exports but produces gibberish while the non-GQA works perfectly). I was wondering if this PR has any implications on the export scripts if you've trained models using NeoX with GQA

**Comment by tiandeyu-cs** [comment]
This PR does not change GQA models; it only fix a bug in __calculating__ GQA. I do not think this PR can affect model exporting.

**Comment by aflah02** [comment]
> This PR does not change GQA models; it only fix a bug in **calculating** GQA. I do not think this PR can affect model exporting.

Thanks! I actually used your PR as reference and asked ChatGPT to make the corresponding changes in the export file. It cooked up some incorrect versions but the final version now converts my GQA models properly and they output coherent stuff while earlier it generated gibberish post conversion. I honestly was too sleepy and didn't look too closely apart from seeing inference results but yeah

**Pull request merged**
