### PR TITLE
make fused kernels installation optional

### PR DESCRIPTION
**Pull request by sdtblck**
This should let you run training without installing fused kernels, if you aren't using them, but will raise an error if you configure them without installing.

### CODE REVIEW

**Comment by OliveS9** [comment]
Has the sub-project of "make fused kernels installation optional " been completed yet? Thanks a lot.

**Review by StellaAthena — APPROVED** [review]
I uninstalled fused kernels and ran a test without any issue. I then re-enabled softmax fusion and got
```
====================================================================================================
ERROR: Fused kernels configured but not installed. Please run `python /home/mchorse/gpt-neox/megatron/fused_kernels/setup.py install` to install them
====================================================================================================
```
as anticipated.

Looks good to me!

**Comment by Mather10** [comment]
> I uninstalled fused kernels and ran a test without any issue. I then re-enabled softmax fusion and got
> 
> ```
> ====================================================================================================
> ERROR: Fused kernels configured but not installed. Please run `python /home/mchorse/gpt-neox/megatron/fused_kernels/setup.py install` to install them
> ====================================================================================================
> ```
> 
> as anticipated.
> 
> Looks good to me!

Why does the error message 

```
====================================================================================================
ERROR: Fused kernels configured but not installed. Please run `python /home/ec2-user/SageMaker/slim_got_neox/gpt-neox/megatron/fused_kernels/setup.py install` to install them
====================================================================================================
```

occur when running "./deepy.py generate.py ./20B_checkpoints/configs/20B.yml "although the tree "make fused kernels installation optional" is checked out and used? Thanks.

**Comment by StellaAthena** [comment]
> > I uninstalled fused kernels and ran a test without any issue. I then re-enabled softmax fusion and got
> > ```
> > ====================================================================================================
> > ERROR: Fused kernels configured but not installed. Please run `python /home/mchorse/gpt-neox/megatron/fused_kernels/setup.py install` to install them
> > ====================================================================================================
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > as anticipated.
> > Looks good to me!
> 
> Why does the error
> 
> ```
> ====================================================================================================
> ERROR: Fused kernels configured but not installed. Please run `python megatron/fused_kernels/setup.py install` to install them
> ====================================================================================================
> ```
> 
> occur when running "./deepy.py generate.py ./20B_checkpoints/configs/20B.yml "although the tree "make fused kernels installation optional" is checked out and used? Thanks.

Because the 20B config file says 
```python
  "scaled-upper-triang-masked-softmax-fusion": true,
  "bias-gelu-fusion": true,
```

**Pull request merged**
