### PR TITLE
LayerNorm Refactor

### PR DESCRIPTION
**Pull request by aurelion-source**
Adds:
- Apex's rmsnorm
- TransformerEngine's rmsnorm and layernorm

### CODE REVIEW

**Comment by aurelion-source** [comment]
Report comparing performance of norm implementations (including TF and Apex) can be found here: https://api.wandb.ai/links/shetano-personal/o0tz0qy3

Default 125M config was used on 4 x NVIDIA A100-SXM4-80GB

**Comment by Quentin-Anthony** [comment]
resolves https://github.com/EleutherAI/gpt-neox/pull/1235 and https://github.com/EleutherAI/gpt-neox/pull/1265

**Comment by Quentin-Anthony** [comment]
Rebased onto upstream `main`. Doing the close + reopen trick to handle diff.

**Review by Quentin-Anthony — APPROVED** [review]
LGTM

**Pull request merged**
