### PR TITLE
Hacky FlashAttn 2 support

### PR DESCRIPTION
**Pull request by haileyschoelkopf**
Enables flash attention v2 for model training. 

TODOs that I definitely won't get to pre-ICML:
- Do we want to retain support for Flash attn version 1?
- retain support for KV-packed flash attention for inference (haven't checked what this entails yet)
- retain Triton support (possibly check that the Triton updated FA2 kernel works with NeoX?)

### CODE REVIEW

**Comment by chris-ha458** [comment]
> * Do we want to retain support for Flash attn version 1?
If I read the paper correctly, Flash V2 is comprised of two components.
One is further optimization of the Flash V2 attention and the second is improved work partitioning between warps and different parallelism (sequence parallelism if i'm correct)

While the former parts regard more fundamental aspects around memory access and attention calculations, the latter might be more hardware specific and difficult to support across different architectures or generations.

I haven't done a deep dive into flash v2 code, (and tbh, I will likely never) but if these two are neatly separated, it might be a good idea to fully move forward with the first part while leaving the second part for later implementation or selection.

**Comment by haileyschoelkopf** [comment]
I think you're right! It probably makes sense to retain Flash v1 support and use that if a user has installed a pre-2.0 version of the package, because Flash v2 still doesn't support Turing GPUs.

**Comment by zhangir-azerbayev** [comment]
Using this PR caused a training run to fail when computing validation loss. I successfully completed a run with the same config before merging this change and upgrading flash-attn to 2.0.0.post1. This is the stack trace: 
```
 samples/sec: 13.340 | iteration     1000/   10000 | elapsed time per iteration (ms): 9595.6 | learning rate: 2.989E-05 | approx flops per GPU: 193.1TFLOPS | lm_loss: 8.667910E-01 | loss scale: 256.0 | number of skipped iterations:   0 | number of nan iterations:   0 |
time (ms) | forward: 2277.35 | backward: 7152.80 | backward-backward: 7152.69 | backward-allreduce: 0.00 | optimizer: 163.86 | batch generator: 3.39
Traceback (most recent call last):
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/train.py", line 27, in <module>
Traceback (most recent call last):
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/train.py", line 27, in <module>
Traceback (most recent call last):
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/train.py", line 27, in <module>
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/train.py", line 27, in <module>
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/train.py", line 27, in <module>
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/train.py", line 27, in <module>
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/train.py", line 27, in <module>
    pretrain(neox_args=neox_args)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 226, in pretrain
    pretrain(neox_args=neox_args)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 226, in pretrain
    pretrain(neox_args=neox_args)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 226, in pretrain
    pretrain(neox_args=neox_args)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 226, in pretrain
    pretrain(neox_args=neox_args)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 226, in pretrain
    pretrain(neox_args=neox_args)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 226, in pretrain
    pretrain(neox_args=neox_args)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 226, in pretrain
            iteration = train(    iteration = train(    iteration = train(
iteration = train(
iteration = train(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 849, in train

  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 849, in train

  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 849, in train
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 849, in train
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 849, in train
        evaluate_and_print_results(evaluate_and_print_results(

  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 964, in evaluate_and_print_results
      File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 964, in evaluate_and_print_results
        evaluate_and_print_results(evaluate_and_print_results(evaluate_and_print_results(


  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 964, in evaluate_and_print_results
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 964, in evaluate_and_print_results
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 964, in evaluate_and_print_results
        total_loss_dict = evaluate(total_loss_dict = evaluate(

  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 910, in evaluate
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 910, in evaluate
            total_loss_dict = evaluate(total_loss_dict = evaluate(total_loss_dict = evaluate(


  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 910, in evaluate
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 910, in evaluate
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 910, in evaluate
            iteration = train(loss = forward_step_fn(loss = forward_step_fn(
            

  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 849, in train
loss = forward_step_fn(loss = forward_step_fn(loss = forward_step_fn(  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 371, in forward_step
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 371, in forward_step



  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 371, in forward_step
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 371, in forward_step
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 371, in forward_step
        outputs = model((tokens, position_ids, attention_mask), neox_args=neox_args)outputs = model((tokens, position_ids, attention_mask), neox_args=neox_args)

              File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
outputs = model((tokens, position_ids, attention_mask), neox_args=neox_args)outputs = model((tokens, position_ids, attention_mask), neox_args=neox_args)    outputs = model((tokens, position_ids, attention_mask), neox_args=neox_args)

evaluate_and_print_results(
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl

  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 964, in evaluate_and_print_results
    total_loss_dict = evaluate(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 910, in evaluate
    loss = forward_step_fn(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 371, in forward_step
    outputs = model((tokens, position_ids, attention_mask), neox_args=neox_args)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
                return forward_call(*input, **kwargs)        return forward_call(*input, **kwargs)return forward_call(*input, **kwargs)
return forward_call(*input, **kwargs)return forward_call(*input, **kwargs)

  File "/home/za2514/DeeperSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn


  File "/home/za2514/DeeperSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
  File "/home/za2514/DeeperSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
  File "/home/za2514/DeeperSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
  File "/home/za2514/DeeperSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
return forward_call(*input, **kwargs)
  File "/home/za2514/DeeperSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
                ret_val = func(*args, **kwargs)    ret_val = func(*args, **kwargs)    ret_val = func(*args, **kwargs)ret_val = func(*args, **kwargs)
ret_val = func(*args, **kwargs)
ret_val = func(*args, **kwargs)

  File "/home/za2514/DeeperSpeed/deepspeed/runtime/engine.py", line 1731, in forward

  File "/home/za2514/DeeperSpeed/deepspeed/runtime/engine.py", line 1731, in forward
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/engine.py", line 1731, in forward
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/engine.py", line 1731, in forward
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/engine.py", line 1731, in forward

  File "/home/za2514/DeeperSpeed/deepspeed/runtime/engine.py", line 1731, in forward
        loss = self.module(*inputs, **kwargs)        loss = self.module(*inputs, **kwargs)
        loss = self.module(*inputs, **kwargs)loss = self.module(*inputs, **kwargs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
loss = self.module(*inputs, **kwargs)loss = self.module(*inputs, **kwargs)

  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl


  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 186, in forward
        return forward_call(*input, **kwargs)return forward_call(*input, **kwargs)

  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 186, in forward
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 186, in forward
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 186, in forward
        return forward_call(*input, **kwargs)return forward_call(*input, **kwargs)

  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 186, in forward
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 186, in forward
    iteration = train(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 849, in train
    evaluate_and_print_results(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 964, in evaluate_and_print_results
    total_loss_dict = evaluate(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 910, in evaluate
    loss = forward_step_fn(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 371, in forward_step
        x = self.activation_checkpoint_func(x = self.activation_checkpoint_func(

  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 713, in checkpoint
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 713, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 555, in forward
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 555, in forward
    outputs = run_function(*inputs_cuda)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 163, in exec_func
    outputs = run_function(*inputs_cuda)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 163, in exec_func
    outputs = model((tokens, position_ids, attention_mask), neox_args=neox_args)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/za2514/DeeperSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/engine.py", line 1731, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 186, in forward
        x = self.activation_checkpoint_func(x = self.activation_checkpoint_func(    

    x = self.activation_checkpoint_func(  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 713, in checkpoint
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 713, in checkpoint
        x = self.activation_checkpoint_func(
inputs = layer(inputs)x = self.activation_checkpoint_func(
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 713, in checkpoint


  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 713, in checkpoint
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 713, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
      File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 555, in forward
CheckpointFunction.apply(function, all_outputs, *args)    
    CheckpointFunction.apply(function, all_outputs, *args)  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 555, in forward
return forward_call(*input, **kwargs)    
    
CheckpointFunction.apply(function, all_outputs, *args)  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 555, in forward
CheckpointFunction.apply(function, all_outputs, *args)  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 914, in forward


  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 555, in forward
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 555, in forward
    outputs = run_function(*inputs_cuda)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 163, in exec_func
    outputs = run_function(*inputs_cuda)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 163, in exec_func
    outputs = run_function(*inputs_cuda)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 163, in exec_func
    outputs = run_function(*inputs_cuda)
      File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 163, in exec_func
outputs = run_function(*inputs_cuda)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 163, in exec_func
    inputs = layer(inputs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 914, in forward
    inputs = layer(inputs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 914, in forward
    inputs = layer(inputs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 914, in forward
    inputs = layer(inputs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 914, in forward
    inputs = layer(inputs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 914, in forward
    inputs = layer(inputs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 914, in forward
    return super().forward(hidden_states, attention_mask), attention_mask
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 858, in forward
        return super().forward(hidden_states, attention_mask), attention_maskreturn super().forward(hidden_states, attention_mask), attention_mask        
    
return super().forward(hidden_states, attention_mask), attention_mask    return super().forward(hidden_states, attention_mask), attention_mask  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 858, in forward
return super().forward(hidden_states, attention_mask), attention_mask  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 858, in forward

Traceback (most recent call last):
return super().forward(hidden_states, attention_mask), attention_mask

  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 858, in forward

  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 858, in forward
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 858, in forward
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 858, in forward
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/train.py", line 27, in <module>
    pretrain(neox_args=neox_args)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 226, in pretrain
    iteration = train(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 849, in train
    evaluate_and_print_results(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 964, in evaluate_and_print_results
    total_loss_dict = evaluate(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 910, in evaluate
    loss = forward_step_fn(
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/training.py", line 371, in forward_step
    outputs = model((tokens, position_ids, attention_mask), neox_args=neox_args)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/za2514/DeeperSpeed/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
    ret_val = func(*args, **kwargs)
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/engine.py", line 1731, in forward
    loss = self.module(*inputs, **kwargs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 186, in forward
    x = self.activation_checkpoint_func(
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 713, in checkpoint
    CheckpointFunction.apply(function, all_outputs, *args)
  File "/home/za2514/DeeperSpeed/deepspeed/runtime/activation_checkpointing/checkpointing.py", line 555, in forward
    outputs = run_function(*inputs_cuda)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/utils.py", line 163, in exec_func
    inputs = layer(inputs)
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 914, in forward
    return super().forward(hidden_states, attention_mask), attention_mask
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 858, in forward
    attention_output, attention_bias = self.attention(
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 685, in forward
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 537, in flash_attention
    output = self.flash_kv_fn(
TypeError: 'NoneType' object is not callable
wandb: Waiting for W&B process to finish... (failed 1).
    attention_output, attention_bias = self.attention(
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 685, in forward
    attention_output, attention_bias = self.attention(
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 685, in forward
    attention_output, attention_bias = self.attention(
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 685, in forward
    attention_output, attention_bias = self.attention(
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 685, in forward
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 537, in flash_attention
    attention_output, attention_bias = self.attention(
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    attention_output, attention_bias = self.attention(
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 685, in forward
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 685, in forward
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 537, in flash_attention
    attention_output, attention_bias = self.attention(
  File "/home/hailey81/miniconda3/envs/llmath_flashv2/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 685, in forward
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 537, in flash_attention
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 537, in flash_attention
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 537, in flash_attention
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 537, in flash_attention
    output = self.flash_kv_fn(
TypeError: 'NoneType' object is not callable
    output = self.flash_kv_fn(
TypeError: 'NoneType' object is not callable
    output = self.flash_kv_fn(
TypeError: 'NoneType' object is not callable
    output = self.flash_kv_fn(
TypeError: 'NoneType' object is not callable
    output = self.flash_kv_fn(
TypeError: 'NoneType' object is not callable
    output = self.flash_kv_fn(
TypeError: 'NoneType' object is not callable
    context_layer = self.flash_attention(query_layer, key_layer, value_layer)
  File "/nobackup/scratch/usr/za2514/math-lm/gpt-neox/megatron/model/transformer.py", line 537, in flash_attention
    output = self.flash_kv_fn(
TypeError: 'NoneType' object is not callable
wandb: - 0.000 MB of 0.000 MB uploaded (0.000 MB deduped)
wandb: 
wandb: Run history:
wandb: runtime/flops_per_sec_per_gpu ▁▄▄▄▅▄▅▄▄▅▄▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▆▇▇▇▇██▇█▇███
wandb:        runtime/iteration_time █▅▅▅▄▄▄▅▄▄▅▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▃▂▂▂▂▁▁▂▁▂▁▁▁
wandb:       runtime/samples_per_sec ▁▄▄▄▅▄▅▄▄▅▄▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▅▆▇▇▇▇██▇█▇███
wandb:               timers/backward ▄██▇▇▇▇▇▇▇▇▇▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▅▃▄▃▁▂▂▁▂▂▂▁▁
wandb:     timers/backward-allreduce ▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:      timers/backward-backward ▄██▇▇▇▇▇▇▇▇▇▆▆▆▆▆▆▆▆▆▆▆▆▆▆▆▅▃▄▃▁▂▂▁▂▂▂▁▁
wandb:        timers/batch generator █▄▂▃▃▃▃▄▄▁▄▄▂▂▂▃▂▃▅▄▅▃▂▁▂▂▂▂▂▃▃▂▃▃▂▅▄▂▂▂
wandb:                timers/forward █▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁▁
wandb:              timers/optimizer █▇▇▇▇▇▇▇▇▇▇▂▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▁▇▇▁▇▇▇▇▇▇▆▇▆
wandb:           train/learning_rate ▁▁▂▂▂▃▃▃▄▄▄▅▅▆▆▆▇▇▇█████████████████████
wandb:                 train/lm_loss █▄▆▆▅▅▅▄▄▄▅▃▃▄▄▃▄▄▃▅▂▂▄▅▁▃▄▄▃▅▆▂▂▃▃▃▃▄▄▃
wandb:              train/loss_scale ███████████▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▄▂▁▁▁▁▁▁▁▁▁▁▁▁
wandb: 
wandb: Run summary:
wandb: runtime/flops_per_sec_per_gpu 193067740626595.9
wandb:        runtime/iteration_time 9.59555
wandb:       runtime/samples_per_sec 13.33951
wandb:               timers/backward 7.1528
wandb:     timers/backward-allreduce 0.0
wandb:      timers/backward-backward 7.15269
wandb:        timers/batch generator 0.00339
wandb:                timers/forward 2.27735
wandb:              timers/optimizer 0.16386
wandb:           train/learning_rate 3e-05
wandb:                 train/lm_loss 0.82912
wandb:              train/loss_scale 256.0
```

**Comment by haileyschoelkopf** [comment]
Ah oof oops. I for some reason thought that we only use the KV-packed flash attn in generation, making flash_kv_fn unused for our current use.

If I have time I can try and go fix this this week. A quick workaround I think should be to set self.flash_kv_func = `flash_attn_varlen_kvpacked_func
`.

**Comment by haileyschoelkopf** [comment]
Yes, this can now be closed!

**Pull request closed without merging**
