### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by sdtblck**

### CODE REVIEW

**Comment by EricHallahan** [comment]
Switch to CUDA 11.3?

**Comment by StellaAthena** [comment]
@sdtblck Eric is wondering why you’re not using CUDA == 11.3

**Comment by StellaAthena** [comment]
> Switch to CUDA 11.3?

@sdtblck Ping

**Comment by StellaAthena** [comment]
@EricHallahan @sdtblck is this even state-of-the-art anymore?

**Comment by EricHallahan** [comment]
Technically the latest version of PyTorch is [v1.10.2](https://github.com/pytorch/pytorch/releases/tag/v1.10.2).

**Comment by StellaAthena** [comment]
Closing as outdated

**Pull request closed without merging**
