### PR TITLE
add merge script

### PR DESCRIPTION
**Pull request by Mistobaan**
re-based version of https://github.com/EleutherAI/gpt-neox/pull/466

Tested only on 20B

### CODE REVIEW

**Comment by StellaAthena** [comment]
@Mistobaan in the referenced PR, it is found that the merge reduces performance. Is this still the case in your verison?

**Comment by Mistobaan** [comment]
Not sure, which benchmarks are we running, and on what hardware?

**Comment by EricHallahan** [comment]
@Mistobaan https://github.com/EleutherAI/gpt-neox/pull/466#issuecomment-997517986

**Comment by Mistobaan** [comment]
oh, I see, you mean the accuracy of the model is not the same when the weights are merged. Yes this is still the case with this PR.

**Pull request closed without merging**
