### PR TITLE
Add SPMTokenizer to preprocess_data.py

### PR DESCRIPTION
**Pull request by Ktakuya332C**
Hello! Thank you for open sourcing this amazing repository.

I've noticed that although the sentencepiece tokenizer is compatible with the training scripts, there is no SPMTokenizer option available in `tokenizer-type` argument of `preprocess_data.py`.

To address this, this PR adds an option to use the SPMTokenizer. This will be very useful for users who want to train LLMs on languages other than English. Though it's possible for me to add this line myself, I believe explicitly including the option will be helpful for other users too.

Thank you for taking the time to review this PR.

### CODE REVIEW

**Comment by StellaAthena** [comment]
Thank you for this pull request! This seems to be an oversight on our part when merging the SPM Tokenizer PR. I’ll verify that this runs without issue and then merge it.

**Comment by StellaAthena** [comment]
@Ktakuya332C how have you been calling this? I tried downloading the T5 tokenizer from the HF Hub and ran `python tools/preprocess_data.py --tokenizer-type SPMTokenizer --input data/enwik8 --output-prefix test --vocab-file tokenizer.json` but got the following error
```
mchorse@jessica-a40-0:~/gpt-neox$ python tools/preprocess_data.py --tokenizer-type SPMTokenizer --input data/enwik8 --output-prefix test --vocab-file tokenizer.json
> building SPMTokenizer tokenizer ...
Traceback (most recent call last):
  File "tools/preprocess_data.py", line 244, in <module>
    main()
  File "tools/preprocess_data.py", line 174, in main
    tokenizer = build_tokenizer(args)
  File "/home/mchorse/gpt-neox/megatron/tokenizer/tokenizer.py", line 43, in build_tokenizer
    tokenizer = SentencePieceTokenizer(args.vocab_file)
  File "/home/mchorse/gpt-neox/megatron/tokenizer/tokenizer.py", line 192, in __init__
    self.tokenizer = spm.SentencePieceProcessor(model_file=vocab_file)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 447, in Init
    self.Load(model_file=model_file, model_proto=model_proto)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 905, in Load
    return self.LoadFromFile(model_file)
  File "/usr/local/lib/python3.8/dist-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto->ParseFromArray(serialized.data(), serialized.size())] 
```

**Comment by Ktakuya332C** [comment]
Thank you for validating this PR !

Here is a minimal sample to use the SPMTokenizer in preprocess_data.py
```
$ # Create docker container to run the script
$ git clone git@github.com:Ktakuya332C/gpt-neox.git
$ cd gpt-neox
$ git checkout add-spm-to-preprocess
$ docker build . -t gpt-neox
$ docker run -it --rm -v $PWD:/home/mchorse gpt-neox bash

$ # Run the script
$ mkdir data
$ curl https://data.deepai.org/enwik8.zip | zcat | head -n 10000 > data/enwik8.txt
$ wget -O data/speice.model https://huggingface.co/t5-base/resolve/main/spiece.model
$ python tools/preprocess_data.py \
    --tokenizer-type SPMTokenizer \
    --input data/enwik8.txt \
    --output-prefix data/enwik8 \
    --vocab-file data/speice.model \
    --log-interval 1
```
The `speice.model` file was taken from https://huggingface.co/t5-base/tree/main

I'm not sure whether the name of the option `vocab-file` suits this case, but at least this works with minimal changes.

**Comment by chris-ha458** [comment]
>I'm not sure if the option name vocab-file is the best fit for this case, but at least it works with minimal changes. ( model-file might be more appropriate, but adding a new option just for this tokenizer may not ideal... )

Just to be sure, recent versions of spm outputs both a vocab file (with the vocabulary) and a model file (with merge rules and pretokenization/normalization details)
can the tokenizer work with one but not the other?

**Comment by StellaAthena** [comment]
Do you know what kind of file `speice.model` is? My computer just says it's binary code. My understanding (like @chris-ha458's) is that the the current best practices for T5x is the tokenizer and merges file, which brings them into alignment with other open source libraries like us and `transformers`. It's possible we only support the older version of SPM though? Which may explain why yours worked and mine didn't.

Could you look into this please?

**Comment by chris-ha458** [comment]
the "spiece.model" file is explained by it's name.
It is the "model" portion of a "sentencepiece tokenizer" instance, which is usually composed of a "model" and a "vocabulary". 
(other filename combination include sentencepiece.model, spm.bpe.model etc
)
It may be the "model" of any one of the supported algorithms which are char, word(wordpiece-smt), BPE or Unigram.

The "models" of each algorithms are subtly different, an easy shortcut to understanding is that they encode the merge rules. The merge rules govern how individual subtokens (which themselves might be tokens built with subtokens) combine to become a token in the "vocabulary".  Thus we come to the second part of the constituent of a sentence piece tokenizer. 

atleast for sentencepiece framework, the model file is enough to fully reconstitute and deterministically operate the tokenizer(including the pretokenization, and normalization steps)
It is still useful to have the vocabulary at hand so spm emits one during training.
(this is not relevant for our discussion however)

For the tokenizer.json file used by the [tokenizers](https://github.com/huggingface/tokenizers) library, it includes the pretokenization and 
normalization steps and parameters in the file itself .
however, usually the tokenizer_config.json and/or the special_tokens_map.json file with the special tokens information are also accompanied. These are not strictly necessary.

pythia tokenizer
special_tokens_map.json contains:
{
  "bos_token": "<|endoftext|>",
  "eos_token": "<|endoftext|>",
  "unk_token": "<|endoftext|>"
}

tokenizer_config.json contains:
{
  "add_prefix_space": false,
  "bos_token": "<|endoftext|>",
  "eos_token": "<|endoftext|>",
  "name_or_path": "EleutherAI/gpt-neox-20b",
  "special_tokens_map_file": "privacy_leak_censored",
  "tokenizer_class": "GPTNeoXTokenizer",
  "unk_token": "<|endoftext|>"
}
it is easy to see that only one of the two are necessary.
to be honest I cannot see why these cannot be integrated into the tokenizers.json file
however this is for the team developing tokenizers to ponder, discuss, and change (if necessary)

**Comment by chris-ha458** [comment]
as for T5x support, sentencepiece is closely coupled with T5x. 
I am looking into how different transformer frameworks utilize and document tokenizers(hint few do either well) and this is also an important interest.

it is not well documented in T5x unfortunately.
and they refer to the sentencepiece model and vocabulary files as "[Vocabulary](https://github.com/google-research/t5x/blob/main/docs/models.md)" .. I would argue that in tandem they should be called "Model file" but I digress...

judging by their **base model code** for a model (mT5) their
"vocabulary code" indeed imports only the sentencepiece.model file
```
# Vocabulary (shared by encoder and decoder)
VOCABULARY = @seqio.SentencePieceVocabulary()
seqio.SentencePieceVocabulary.sentencepiece_model_file = "gs://t5-data/vocabs/mc4.250000.100extra/sentencepiece.model"
```
So this affirms my beliefs that atleast for how T5x, seqio codebase treats their tokenizer portion,
only the .model file is necessary, .vocab file is unnecessary, and there are no other files to consider.
in case of not using sentencepiece itself for all this processes, (eg using huggingface autotokenizer sentencepiece implementation) there is the specialised issue of stochastic tokenization and its implementation but it is not a pressing issue at this stage. It breaks my heart to acknowledge this but huggingface's spm implementation omits this process with no near term plans to incorporate it. Yet few people care.

Lastly, as far as i know, sentencepiece model format has not undergone any backward or forward incompatible changes.
However, I will look into it.

**Comment by chris-ha458** [comment]
Best way would be for the project to incorporate both as recent versions of sentencepiece and tokenizers as possible
and utilize the appropriate oneaccording to the model submitted.

If that is unfeasible, i would need to think about what would be the best alternative.
I'll look into the code base

**Comment by StellaAthena** [comment]
@chris-ha458 thanks!

**Comment by Ktakuya332C** [comment]
@chris-ha458 Thank you for your comments! I will also look into codebases to find a best way to integrate sentencepiece model/vocab files. ( I'm a little busy right now, so it may take a few days... )

**Comment by chris-ha458** [comment]
Quick comment : the sentencepiece.model format is a "protobuf" or protocol buffer file. 
It is documented in https://protobuf.dev

To open it , you would need the specification file for the version of the protobuf file
Ex "sentencepiece_pb2.py"
And an appropriate protobuf version installed. So far, I've been having difficulty getting those three in line so I couldn't read the files themselves, but usually this is all done internally by Sentencepiece.

The above process is only relevant if you'd like to manually  manage the model like you would do with a tokenzier.json file.

I would like to, but library version dependency management is not my forte.

Also there seems to be no explicit promise that the protobuf files (and to an extent the model files ) would be forward or backwards compatible.

**Comment by chris-ha458** [comment]
after working on huggingface/tokenizers and working with many tokenizers learned for models, 
my conclusion is that it would be difficult to handle this from this codebase.
It would be easier to depend on  hf/tokenizers for this particular function.
Thankfully, similar issues (spm model loading) is being discussed, developed and handled there
and it would be useful to pool development resources and effort ( including mine) to that code base.

If it is decided towards that direction the remaining question would be :
What we require the tokenizer library to do for this gpt-neox esp. regarding sentencepiece libraries.
Which version of tokenizer library to follow : currently requirements.txt lists 0.12.1 but that is 1 year old. I cannot see why we cant depend on atleast 0.13.3. we might need to write tests for the behavior we require both for this feature on backwards compatibility. my understanding that there has not been any breaking changes nor will there be for the forseeable future.

**Comment by chris-ha458** [comment]
For current version (0.13.3) of huggingface tokenizers the tokenizer.json file is stand alone. 
That is the other artifact files(tokenzer_config.json or special_tokenmap.json etc) are legacy files that are not necessary.
They exist for backward compatibility and human readibility, but if necessary could be reconstructed by the tokenizer.json

Same for sentencepiece. the .model file is standalone.
The otherfiles are useful for reading but not necessary for training or inference.

As such, it would be still useful for there to be the other artifact files but the tokenizer.json and sentencepiece.model files would be fully sufficient for our purposes.

Whether to call them the "vocab" "merge rule" "model" is irrelevant. The engineering and academic literature is confuddled enough. it would be sufficient for us to maintain a consistent understanding and naming scheme.
Anyway I believe that this PR should be OK as is.
More documentation might be helpful. 
For instance,  to pointout when using SPM option only protobuf2 .model files from the spm tool is valid. As a sentence-piece unigram model produced by huggingface/tokenizer would have a tokenizer.json form and would not be valid input to SPM tokenizer.

**Comment by Ktakuya332C** [comment]
@chris-ha458 Thank you for your through investigation ! 
In 3, I added a simple assertion to check that the `vocab_file` surely points to a file generated by spm tools, not by huggingface/tokenizers. Please let me know if there seems to be a problem.

I also searched for a way to integrate two types of sentencepiece files ( `.model` file generated by spm tools and `tokenizer.json` file generated by huggingface/tokenizer ) easily, but could not find one. Easiest hack might be to switch spm.SentencePieceTokenizer and corresponding tokenizer from huggingface/tokenizer depending on the name of `vocab_file`, but it seems not right. 

@StellaAthena Do you mind if I ask for your comment? Because I don't know much about sentencepiece tokenizer of huggingface/tokenizers, I'm now not able to integrate these two files seamlessly into SPMTokenizer. Current PR forces the user to use `.model` file generated by spm tools, and doesn't admit `tokenizer.json` generated by huggingface/tokenizer. If this suffices, then please add comment about the documentation as mentioned in the comment of @chris-ha458. If not, sorry, but I plan to retract this PR and give space for others to contribute.

**Comment by chris-ha458** [comment]
My opinion is that it suffices. 
I dont know what you mean by integration. SPM models, regardless of the algorithm, are [protocolbuffers](https://protobuf.dev/), tokenizer models, regardless of the algorithm, are json files.

It *might* be possible to integrate them, or find a way to identify them before feeding them into the proper tokenizer, but in my opinion that would be too much engineering for this project to handle.

Even spm or tokenizer libraries assume that the end users provide the proper version without worrying too much. I assume that the steps taken here, and possibly more friendly error messages if and when necessary would be enough.

**Comment by Ktakuya332C** [comment]
> I dont know what you mean by integration.
>  It might be possible to integrate them, or find a way to identify them before feeding them into the proper tokenizer, but in my opinion that would be too much engineering for this project to handle.

Thank you for clarification. This is my intent.

> possibly more friendly error messages if and when necessary would be enough.

In 5cc4bc5, I changed the error message a little more friendly.

**Comment by StellaAthena** [comment]
@Ktakuya332C

> you mind if I ask for your comment? Because I don't know much about sentencepiece tokenizer of huggingface/tokenizers, I'm now not able to integrate these two files seamlessly into SPMTokenizer. Current PR forces the user to use .model file generated by spm tools, and doesn't admit tokenizer.json generated by huggingface/tokenizer. If this suffices, then please add comment about the documentation as mentioned in the comment of @chris-ha458. If not, sorry, but I plan to retract this PR and give space for others to contribute.

I think that this makes sense, based on your convo with @chris-ha458. This PR is generally looking quite good now, we just need to get one or two people to test it on a clean install and make sure that the documentation is easy to follow.

**Comment by chris-ha458** [comment]
> > It might be possible to integrate them, or **find a way to identify them before feeding them into the proper tokenizer** ...
> Thank you for clarification. This is my intent.
@Ktakuya332C 
1. Currently, the default extension for models from sentencepiece is .model.
for tokenizer, it is tokenizer.json.
For any enduser that have the corresponding correct model but different file extension it is not difficult to change the extension. The models are also small enough that if they were relying on outside links and not the file themselves it would be easy enough to download it and change it before input.

2. Each tokenizer libraries emit errors for malformed model inputs (their interface may vary).

So my opinion is that your approach is practical enough. Again, we could do something above and beyond but I don't feel any more software engineering is not justified.
We should only try to test and ensure correct behavior of what you have implemented already.

3. I agree that it "looks correct" and only needs a bit more testing.

I am out of bandwidth to self initiate the process, but if anyone can provide step by step instructions for expected behavior i can follow them and provide feedback.

When I do gain some more time and resources to do independent testing myself, I will note it here and do so. 
juggling multiple trees including a tokenizer training implementation on this code base and the huggingface tokenizer itself is not helping :(

**Comment by Ktakuya332C** [comment]
As far as I know, the only way to test scripts in the tools directory is manual testing. If there are any other methods to test, please tell me.

I always did manual testing in the following way before merging changes to this branch.
```
$ # Create docker container
$ git clone git@github.com:Ktakuya332C/gpt-neox.git
$ cd gpt-neox
$ git checkout add-spm-to-preprocess
$ docker build . -t gpt-neox

$ # Run the script in container
$ docker run -it --rm -v $PWD:/home/mchorse gpt-neox bash
$ mkdir data
$ curl https://data.deepai.org/enwik8.zip | zcat | head -n 10000 > data/enwik8.txt
$ wget -O data/speice.model https://huggingface.co/t5-base/resolve/main/spiece.model
$ python tools/preprocess_data.py \
    --tokenizer-type SPMTokenizer \
    --input data/enwik8.txt \
    --output-prefix data/enwik8 \
    --vocab-file data/speice.model \
    --log-interval 1
$ echo $?
0
```

I also checked that `preprocess_data.py` at the root directory also works without any errors.
```
$ # Run the script in container
$ docker run -it --rm -v $PWD:/home/mchorse gpt-neox bash
$ wget -O speice.model https://huggingface.co/t5-base/resolve/main/spiece.model
$ python prepare_data.py enwik8   \
    --tokenizer=SPMTokenizer   \
    --data-dir=data   \
    --vocab-file=spiece.model
```

@StellaAthena @chris-ha458 Do you mind if I ask you to follow the commands above, and verify that the both `preprocess_data.py` works without problems ?

**Comment by Ktakuya332C** [comment]
Aside, I noticed that SPMTokenizer was already added in #841 . As a result, this PR now only introduces a tiny assertion I added in 5cc4bc5 . I feel a little bad to ask you two to invest time and effort to verify this nonessential PR, but if you think it does not cost you much, I'm glad if you help me.

**Comment by Ktakuya332C** [comment]
Sorry, I changed my mind. Because the aim of this PR (introducing SPMTokenizer to preprocess_data.py) was already accomplished in another PR, I'll close this PR now. Assertion like this one ( 5cc4bc5 ) might be helpful, but because the assertion itself is a little flaky (naming of the model file generated by google/sentencepiece is not assured to end with `.model` ), it might not worth adding it.

Thank you very much for your effort, especially @chris-ha458 for through investigation.

**Pull request closed without merging**
